import type { Outfit } from '@/types';

export const outfits: Outfit[] = [
  {
    id: 'a_corp_citizen',
    name: 'A Corp. Citizen',
    recipe: '2x Fabric, 1x Rope, 1x Nuovo Fabric, 1x Seed Of Light',
    blunt: 1.1,
    pierce: 0.8,
    slash: 1.0,
    speed: 15,
    keypage: 'Singularity: Decrease incoming status effects by half',
    category: 'Citizen'
  },
  {
    id: 'ambitious_fixer',
    name: 'Ambitious Fixer',
    recipe: '2x Fabric, 2x Books, 1x Book of a Grade 9 Fixer',
    blunt: 0.8,
    pierce: 1.4,
    slash: 1.1,
    speed: 18,
    keypage: 'Slashing Prowess: 25% Chance to boost Slash Damage by 10%. Errand Gone Wrong: When entering combat, apply 3 Haste to self.',
    category: 'Fixer'
  },
  {
    id: 'backstreets_berserker',
    name: 'Backstreets Berserker',
    recipe: '6x Fabric, 1x Wiring, 1x Worn Sledgehammer, 12x Scrap Metal',
    blunt: 1.0,
    pierce: 1.2,
    slash: 1.3,
    speed: 17,
    keypage: 'N/A',
    category: 'Backstreets'
  },
  {
    id: 'backstreets_headhunter',
    name: 'Backstreets Headhunter',
    recipe: '2x Fabric, 1x Wiring, 1x Book',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.3,
    speed: 15,
    keypage: 'Skull Crushing: Increase Blunt damage by 10%',
    category: 'Backstreets'
  },
  {
    id: 'backstreets_investigator',
    name: 'Backstreets Investigator',
    recipe: '3x Fabric, 2x Rope, 1x Wiring',
    blunt: 1.0,
    pierce: 1.2,
    slash: 0.8,
    speed: 16,
    keypage: 'N/A',
    category: 'Backstreets'
  },
  {
    id: 'backstreets_rat',
    name: 'Backstreets Rat',
    recipe: '2x Fabric, 3x Rope, 1x Wiring',
    blunt: 1.3,
    pierce: 1.2,
    slash: 0.7,
    speed: 16,
    keypage: "A Rat's Guide To Survival: Gain increased Dodge frames.",
    category: 'Backstreets'
  },
  {
    id: 'backstreets_mole',
    name: 'Backstreets Mole',
    recipe: '2x Fabric, 3x Rope, 1x Book',
    blunt: 1.2,
    pierce: 1.0,
    slash: 1.0,
    speed: 16,
    keypage: 'Skewing: Increase Pierce damage by 10%',
    category: 'Backstreets'
  },
  {
    id: 'backstreets_scum',
    name: 'Backstreets Scum',
    recipe: '3x Fabric, 2x Rope, 1x Book',
    blunt: 0.8,
    pierce: 1.0,
    slash: 1.0,
    speed: 14,
    keypage: 'Cowardice: Gain increased Speed when reaching low Health threshold.',
    category: 'Backstreets'
  },
  {
    id: 'backstreets_survivor',
    name: 'Backstreets Survivor',
    recipe: '2x Fabric, 2x Scrap Metal, 1x Wiring, 1x Book',
    blunt: 1.0,
    pierce: 1.2,
    slash: 1.2,
    speed: 17,
    keypage: 'Experience: N/A',
    category: 'Backstreets'
  },
  {
    id: 'bartender',
    name: 'Bartender',
    recipe: '1x Nuovo Fabric, 1x Book',
    blunt: 1.2,
    pierce: 1.2,
    slash: 0.7,
    speed: 15,
    keypage: 'N/A',
    category: 'Service'
  },
  {
    id: 'beak',
    name: 'Beak',
    recipe: '1x Book, 1x Nuovo Fabric, 1x Sanity Ampule',
    blunt: 0.8,
    pierce: 1.2,
    slash: 1.0,
    speed: 17,
    keypage: 'N/A',
    category: 'Fixer'
  },
  {
    id: 'black_silence',
    name: 'Black Silence',
    recipe: '2x Wiring, 2x Shimmering Fabric, 1x Rope, 2x Fragment of Silence, 2x Fabric, 3x Nuovo Fabric',
    blunt: 0.8,
    pierce: 1.1,
    slash: 1.0,
    speed: 17,
    keypage: 'A Fighter that Never Retreats: On Emotion Level increase, gain 2 Protection for 20 seconds and 1 Value Power Up for 2 minutes. Clenched Grudge: Gain more stamina when hitting someone.',
    category: 'Legendary'
  },
  {
    id: 'blade_lineage',
    name: 'Blade Lineage',
    recipe: '3x Fabric, 2x Book of Blade Lineage, 1x Rope',
    blunt: 1.0,
    pierce: 1.3,
    slash: 0.7,
    speed: 16,
    keypage: 'Sanguine Plum Blossom: On [Critical Strike] inflict 1 Red Plum Blossom on the target. If the target has 10+ Red Plum Blossom inflict 3 Defense Down with 1 second cooldown. Yield My Flesh - To Claim Their Bones: If in Blade Lineage Office, gain \'Yield My Flesh\' page (2 Light Counter).',
    category: 'Syndicate'
  },
  {
    id: 'blade_lineage_mentor',
    name: 'Blade Lineage Mentor',
    recipe: '3x Fabric, 2x Book of Blade Lineage, 1x Rope',
    blunt: 1.3,
    pierce: 1.0,
    slash: 0.7,
    speed: 16,
    keypage: 'Unrelenting: If User has 5+ Poise Potency, when taking damage that would bring you below 1 Health, nullify the damage for one hit. Does not proc on [Auto Execute]. Yield My Flesh - To Claim Their Bones.',
    category: 'Syndicate'
  },
  {
    id: 'blade_lineage_salsu',
    name: 'Blade Lineage Salsu',
    recipe: '3x Fabric, 2x Book of Blade Lineage, 1x Rope',
    blunt: 1.3,
    pierce: 1.0,
    slash: 0.7,
    speed: 16,
    keypage: 'Poised: [Clash Win] Gain 5 Poise. Yield My Flesh - To Claim Their Bones.',
    category: 'Syndicate'
  },
  {
    id: 'brawler',
    name: 'Brawler',
    recipe: '3x Fabric, 2x Book, 1x Rope, 1x Organ',
    blunt: 0.6,
    pierce: 1.0,
    slash: 1.2,
    speed: 13,
    keypage: 'Cold-Hard Fists: If user has "Fist" Weapon equipped, Increase M1 Damage by 10%.',
    category: 'Combat'
  },
  {
    id: 'brute_fixer',
    name: 'Brute Fixer',
    recipe: '3x Wiring, 2x Scrap Metal, 1x Nuovo Fabric, 1x Vitality Ampule',
    blunt: 0.7,
    pierce: 1.3,
    slash: 0.7,
    speed: 14,
    keypage: 'Health Hauler: If you take more than 20 damage in a single hit, reduce the damage by 4 and gain 5 Regen up.',
    category: 'Fixer'
  },
  {
    id: 'butchers_attire',
    name: "Butcher's Attire",
    recipe: '3x Fabric, 1x Rope, 1x Raw Meat, 1x Organs',
    blunt: 1.0,
    pierce: 1.2,
    slash: 0.7,
    speed: 14,
    keypage: 'Emergency Rations: Increased natural regeneration rates by 20%. Talented Chef: N/A',
    category: 'Service'
  },
  {
    id: 'butler_fixer',
    name: 'Butler Fixer',
    recipe: '3x Fabric, 1x Nuovo Fabric, 1x Sanity Ampule',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.3,
    speed: 16,
    keypage: 'Butler Style Response: [Clash Win] inflict 3 Sinking on the target.',
    category: 'Fixer'
  },
  {
    id: 'casual_fixer',
    name: 'Casual Fixer',
    recipe: '4x Fabric, 1x Nuovo Fabric, 3x Book',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.3,
    speed: 16,
    keypage: 'Moving Up The Ranks: Gain 25% more EXP.',
    category: 'Fixer'
  },
  {
    id: 'casual_jacket',
    name: 'Casual Jacket',
    recipe: '4x Fabric, 2x Rope',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.0,
    speed: 16,
    keypage: 'N/A',
    category: 'Casual'
  },
  {
    id: 'cinq_association',
    name: 'Cinq Association',
    recipe: '2x Book of Cinq Association, 3x Fabric, 1x Rope',
    blunt: 1.2,
    pierce: 0.7,
    slash: 1.3,
    speed: 18,
    keypage: 'Have At Thee!: Gain 7% more Crit Chance for every 2 Haste (max 25%). One Step Ahead: Gain 2 Haste on Flourishes and 3 Haste on Focused Strike.',
    category: 'Association'
  },
  {
    id: 'cinq_specialist',
    name: 'Cinq Association Specialist',
    recipe: '2x Book of Cinq Association, 3x Fabric, 1x Rope',
    blunt: 1.2,
    pierce: 0.7,
    slash: 1.3,
    speed: 18,
    keypage: 'Have At Thee!. Mentors Counsel: [On Clash Start] Gain 1 Clash Power if your faster than the opponent.',
    category: 'Association'
  },
  {
    id: 'circusgoer',
    name: 'Circusgoer',
    recipe: '2x Nuovo Fabric, 2x Wiring, 1x Fabric, 1x Distortion Soda',
    blunt: 1.2,
    pierce: 1.2,
    slash: 1.3,
    speed: 19,
    keypage: 'Fools Act: No Passive',
    category: 'Entertainment'
  },
  {
    id: 'claw_executioner',
    name: 'Claw Executioner',
    recipe: '2x Wiring, 3x Shimmering Fabric, 1x Serum W Vial, 3x Scrap Metal, 2x Nuovo Fabric',
    blunt: 1.0,
    pierce: 0.9,
    slash: 1.2,
    speed: 16,
    keypage: 'Tri Serum Brew: Apply or receive debuffs and buffs depending on the Serum you have installed. Serum Injection: Gain unique page "Serum Injection" (4 Light Cost).',
    category: 'Executioner'
  },
  {
    id: 'clean_suit',
    name: 'Clean Suit',
    recipe: '1x Nuovo Fabric, 1x Book, 3x Fabric',
    blunt: 0.8,
    pierce: 1.3,
    slash: 0.8,
    speed: 16,
    keypage: 'Slugger: [When Hit] while in [Hyperarmor] and then hitting the enemy back from the same [Hyperarmor] move makes that move deal 20% more damage.',
    category: 'Corporate'
  },
  {
    id: 'corporative',
    name: 'Corporative',
    recipe: '2x Book, 4x Fabric',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.2,
    speed: 15,
    keypage: 'Standard Procedure: During EGO, Stamina Damage is Halved.',
    category: 'Corporate'
  },
  {
    id: 'dawn_office_fixer',
    name: 'Dawn Office Fixer',
    recipe: '2x Rope, 2x Fabric, 1x Nuovo Fabric, 1x Stigma Workshop Core',
    blunt: 1.0,
    pierce: 0.6,
    slash: 1.2,
    speed: 16,
    keypage: 'Passion: When proccing [Stagger] on a target, inflict 5 Burn.',
    category: 'Fixer'
  },
  {
    id: 'devyat_association',
    name: 'Devyat Association',
    recipe: '1x Rope, 2x Fabric, 1x Nuovo Fabric, 1x Sanity Ampule',
    blunt: 0.6,
    pierce: 1.0,
    slash: 1.4,
    speed: 16,
    keypage: 'Emergency Rations: Increased natural regeneration rates by 20%.',
    category: 'Association'
  },
  {
    id: 'dieci_key_branch',
    name: 'Dieci Association Key Branch',
    recipe: '2x Book of Dieci Association, 3x Fabric, 1x Rope',
    blunt: 1.3,
    pierce: 0.8,
    slash: 0.8,
    speed: 17,
    keypage: 'Enlightenment: Charged Attacks Inflict 4 Sinking and Gain 6 Shield HP. Sinking Knowledge: [When Hit] whilst having Shield HP inflict 2 Sinking on the attacker.',
    category: 'Association'
  },
  {
    id: 'dieci_fist_branch',
    name: 'Dieci Association Fist Branch',
    recipe: '2x Book of Dieci Association, 3x Fabric, 1x Rope',
    blunt: 0.8,
    pierce: 1.3,
    slash: 0.9,
    speed: 18,
    keypage: 'Sinking Knowledge. Enlightenment: Flourishes now apply 2 Sinking and Give 4 Shield HP. At 20+ Shield HP, deal +15% more Blunt Damage.',
    category: 'Association'
  },
  {
    id: 'death_sentence_pit_fighter',
    name: 'Death Sentence Pit Fighter',
    recipe: '1x Vitality Ampule, 1x Strength Chip Board MK2, 2x Nuovo Fabric, 2x Gears',
    blunt: 1.0,
    pierce: 1.2,
    slash: 0.7,
    speed: 13,
    keypage: 'Glory Scars: Increased Damage to Death Sentence NPCs.',
    category: 'Combat'
  },
  {
    id: 'eerie_bloodfiend',
    name: 'Eerie Bloodfiend',
    recipe: '3x Hardblood Fragment, 2x Rope, 2x Organs, 2x Fabric, 1x Hemobar',
    blunt: 0.8,
    pierce: 1.4,
    slash: 1.1,
    speed: 15,
    keypage: 'N/A',
    category: 'Bloodfiend'
  },
  {
    id: 'family_heir',
    name: 'Family Heir',
    recipe: '1x Nuovo Fabric, 2x Fabric, 1x Sanity Ampule',
    blunt: 1.2,
    pierce: 1.0,
    slash: 0.8,
    speed: 16,
    keypage: 'Suffering: Deal (Enemy Sinking * 1)% more damage (Max. 20%).',
    category: 'Heritage'
  },
  {
    id: 'fullstop_organizer',
    name: 'Full-Stop Organizer',
    recipe: '1x Nuovo Fabric, 3x Ammo Box, 1x Book',
    blunt: 0.8,
    pierce: 1.3,
    slash: 0.8,
    speed: 16,
    keypage: 'AL-HV Round: [On Crit Hit] if [Critical Strike] procs, gain 1 Atelier Logic Ammo.',
    category: 'Fixer'
  },
  {
    id: 'hana_association',
    name: 'Hana Association',
    recipe: '2x Book of Hana Association, 3x Fabric, 1x Rope',
    blunt: 1.0,
    pierce: 0.9,
    slash: 1.0,
    speed: 17,
    keypage: "Brace Up: Take less damage during [Hyperarmor]. For every hit taken above 10 damage during [Hyperarmor], Gain 1 Value Power Up for 10s. Four Trigrams: If in Hana Association Office, gain 'Rotate Trigram' page (0 Light).",
    category: 'Association'
  },
  {
    id: 'index_proselyte',
    name: 'Index Proselyte',
    recipe: 'Book of The Index',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.2,
    speed: 17,
    keypage: "Unlock: If in Index Syndicate Office, gain 'Unlock' page (0 Light) that switches between 3 Forms.",
    category: 'Syndicate'
  },
  {
    id: 'journalist',
    name: 'Journalist',
    recipe: '2x Fabric, 1x Wiring, 1x Rope',
    blunt: 1.0,
    pierce: 1.2,
    slash: 0.8,
    speed: 16,
    keypage: 'N/A',
    category: 'Professional'
  },
  {
    id: 'k_corp_assistant',
    name: 'K Corp. Assistant',
    recipe: '2x Fabric, 1x Rope, 1x K Corp. Ampule',
    blunt: 1.2,
    pierce: 0.8,
    slash: 1.2,
    speed: 16,
    keypage: 'N/A',
    category: 'Corporate'
  },
  {
    id: 'kurokumo_henchman',
    name: 'Kurokumo Henchman',
    recipe: '3x Fabric, 1x Rope, 2x Book of Kurokumo Clan',
    blunt: 0.8,
    pierce: 0.8,
    slash: 1.3,
    speed: 17,
    keypage: 'Dark Cloud Blade: [Clash Win] inflict 3 Bleed Count.',
    category: 'Syndicate'
  },
  {
    id: 'kurokumo_wakashu',
    name: 'Kurokumo Wakashu',
    recipe: '3x Fabric, 1x Rope, 2x Book of Kurokumo Clan',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.2,
    speed: 16,
    keypage: 'Kokuundō: Deal (Enemy Bleed * 1)% more damage (Max. 20%).',
    category: 'Syndicate'
  },
  {
    id: 'leaflet_workshop',
    name: 'Leaflet Workshop',
    recipe: '3x Scrap Metal, 3x Fabric, 2x Wiring',
    blunt: 1.0,
    pierce: 0.9,
    slash: 1.0,
    speed: 15,
    keypage: 'Puffy Brume: Smoke stacks on self now increase outgoing M1 Damage instead of incoming.',
    category: 'Workshop'
  },
  {
    id: 'leaflet_rep',
    name: 'Leaflet Workshop Rep',
    recipe: '3x Scrap Metal, 3x Fabric, 2x Wiring, 1x Leaflet Workshop Steamgun',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.0,
    speed: 15,
    keypage: 'Puffy Brume. Immediate Repairs: Unstagger once every 2 minutes.',
    category: 'Workshop'
  },
  {
    id: 'liu_association',
    name: 'Liu Association',
    recipe: '3x Fabric, 1x Rope, 2x Book of Liu Association',
    blunt: 0.6,
    pierce: 1.4,
    slash: 1.0,
    speed: 15,
    keypage: "Fervor: Gain 2 Value Power Up while in Emotion Level II. Hugging Fire, Sitting on Brushwood: [On Hit] with Pages that apply Burn to the target, inflict 5 stamina damage. Ignite Weaponry: If in Liu Association Office, gain 'Ignite Weaponry' page (1 Light).",
    category: 'Association'
  },
  {
    id: 'liu_operative',
    name: 'Liu Association Operative',
    recipe: '3x Fabric, 1x Rope, 2x Book of Liu Association',
    blunt: 1.2,
    pierce: 0.8,
    slash: 0.8,
    speed: 15,
    keypage: 'Hugging Fire, Sitting on Brushwood. Firm As A Great Mountain: Whenever your Emotion level rises, gain 7.5% Health. Ignite Weaponry.',
    category: 'Association'
  },
  {
    id: 'liu_specialist',
    name: 'Liu Association Specialist',
    recipe: '3x Fabric, 1x Rope, 2x Book of Liu Association',
    blunt: 0.8,
    pierce: 1.2,
    slash: 0.8,
    speed: 15,
    keypage: 'Fervor. Firm As A Great Mountain. Ignite Weaponry.',
    category: 'Association'
  },
  {
    id: 'lone_fixer',
    name: 'Lone Fixer',
    recipe: '3x Scrap Metal, 2x Fabric, 1x Book',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.1,
    speed: 16,
    keypage: 'Lone Fixer: If you have no allies (Not being in an Office), gain 1 Value Power Up.',
    category: 'Fixer'
  },
  {
    id: 'middle_little_sibling',
    name: 'Middle Little Sibling',
    recipe: '3x Fabric, 1x Rope, 1x Book of The Middle (Starter)',
    blunt: 1.2,
    pierce: 1.0,
    slash: 0.8,
    speed: 17,
    keypage: 'Little Vengeance: If target has Paralyze stacks, increase damage by 10%. Enhancement Tattoos: Charged attacks, parrying flourishes and parrying [Guard Break] Gain 1 Enhancement Tattoos.',
    category: 'Syndicate'
  },
  {
    id: 'middle_big_sibling',
    name: 'Middle Big Sibling',
    recipe: '3x Fabric, 1x Nuovo Fabric, 1x Book, 1x Book of The Big Brother of the Middle',
    blunt: 1.5,
    pierce: 0.7,
    slash: 0.7,
    speed: 18,
    keypage: 'Domineer: Anyone who deals less than 5 damage when hitting you gets their sp reduced by 2. Enhancement Tattoos.',
    category: 'Syndicate'
  },
  {
    id: 'multicrack_rep',
    name: 'Multicrack Office Rep',
    recipe: '2x Fabric, 1x Nuovo Fabric, 1x Book',
    blunt: 1.3,
    pierce: 1.0,
    slash: 0.7,
    speed: 15,
    keypage: 'N/A',
    category: 'Fixer'
  },
  {
    id: 'n_corp_inquisitor',
    name: 'N Corp. Inquisitor',
    recipe: '2x Fabric, 2x Rope, 2x Scrap Metal, 1x Book of The One Who Grips',
    blunt: 1.5,
    pierce: 0.8,
    slash: 1.0,
    speed: 14,
    keypage: 'Thou Shalt Hammer: Receive Buffs from N Corp. The One Who Grips.',
    category: 'Corporate'
  },
  {
    id: 'n_corp_one_who_grips',
    name: 'N Corp. The One Who Grips',
    recipe: '3x Fabric, 1x Rope, 1x Scrap Metal, 1x Book of The One Who Grips',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.0,
    speed: 14,
    keypage: 'Bliss of Execution: Killing an enemy now grants 2 Haste and 5 Value Power Up for 10 seconds. Whistles: Upon [Guard Break] someone, Grant 1 Fanatic 15% damage buff to any nearby ally that has N Corp. Inquisitor outfit on.',
    category: 'Corporate'
  },
  {
    id: 'nest_citizen',
    name: 'Nest Citizen',
    recipe: '2x Fabric, 1x Rope, 1x Wiring',
    blunt: 0.8,
    pierce: 1.0,
    slash: 1.3,
    speed: 16,
    keypage: 'N/A',
    category: 'Citizen'
  },
  {
    id: 'nest_lurker',
    name: 'Nest Lurker',
    recipe: '2x Fabric, 1x Rope, 1x Wiring',
    blunt: 0.8,
    pierce: 1.3,
    slash: 1.0,
    speed: 16,
    keypage: 'N/A',
    category: 'Citizen'
  },
  {
    id: 'nest_researcher',
    name: 'Nest Researcher',
    recipe: '1x Book, 1x Nuovo Fabric, 1x K Corp. Ampule',
    blunt: 0.8,
    pierce: 1.0,
    slash: 1.3,
    speed: 16,
    keypage: 'Experimental Rat: K Corp. Ampules have less drawbacks.',
    category: 'Research'
  },
  {
    id: 'night_awl_associate',
    name: 'Night Awl Associate',
    recipe: '2x Fabric, 2x Nuovo Fabric, 1x Rope, 1x Book of Legacy, 1x Book of The Library, 1x Dagger',
    blunt: 1.2,
    pierce: 0.8,
    slash: 1.0,
    speed: 16,
    keypage: 'Stiletto: Increase/Decrease resistance of the target by (-0.3 Blunt +0.3 Pierce - 0.3 Slash).',
    category: 'Association'
  },
  {
    id: 'old_boatman',
    name: 'Old Boatman',
    recipe: 'Book of Legacy',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.0,
    speed: 15,
    keypage: 'N/A',
    category: 'Legacy'
  },
  {
    id: 'old_reaper',
    name: 'Old Reaper',
    recipe: 'Book of Legacy',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.0,
    speed: 15,
    keypage: 'N/A',
    category: 'Legacy'
  },
  {
    id: 'old_whaler',
    name: 'Old Whaler',
    recipe: 'Book of Legacy',
    blunt: 0.8,
    pierce: 1.0,
    slash: 1.0,
    speed: 15,
    keypage: 'N/A',
    category: 'Legacy'
  },
  {
    id: 'outskirts_wanderer',
    name: 'Outskirts Wanderer',
    recipe: '2x Book, 1x Nuovo Fabric, 2x Fabric',
    blunt: 1.0,
    pierce: 1.2,
    slash: 1.0,
    speed: 16,
    keypage: 'Overcome Horrors: Deal 20% more damage against players with E.G.O activated.',
    category: 'Wanderer'
  },
  {
    id: 'outskirts_runner',
    name: 'Outskirts Runner Jumpsuit',
    recipe: '1x Book of a Grade 7 Fixer, 1x Sanity Ampule, 1x Nuovo Fabric, 2x Fabric',
    blunt: 0.8,
    pierce: 1.2,
    slash: 1.3,
    speed: 18,
    keypage: 'Hoarder: Increases Inventory Carry Capacity by 45.',
    category: 'Wanderer'
  },
  {
    id: 'parade_bloodfiend',
    name: 'Parade Bloodfiend',
    recipe: '3x Hardblood Fragment, 2x Rope, 2x Organs, 2x Fabric, 1x Hemobar',
    blunt: 1.2,
    pierce: 1.2,
    slash: 1.0,
    speed: 18,
    keypage: 'N/A',
    category: 'Bloodfiend'
  },
  {
    id: 'whaling_captain',
    name: 'Whaling Crew Captain',
    recipe: '1x Gasharpoon, 2x Mermaid Skin, 3x Fabric, 1x Rope',
    blunt: 1.2,
    pierce: 0.8,
    slash: 1.0,
    speed: 15,
    keypage: 'Overheated Harpoon: [On Hit] Coin3 of Gasharpoon Critical Attack, Gain 1 Overheated Gasharpoon. Overheated Gasharpoon give Gasharpoon Critical Attack +4 Value Power Up.',
    category: 'Whaling'
  },
  {
    id: 'whaling_harpooner',
    name: 'Whaling Crew Harpooner',
    recipe: '2x Mermaid Skin, 3x Fabric, 1x Rope',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.2,
    speed: 15,
    keypage: 'Sharpened Harpoon: On [Critical Strike], apply 4 Bleed. (10 second cooldown)',
    category: 'Whaling'
  },
  {
    id: 'pointilist_uniform',
    name: "Pointilist's Uniform",
    recipe: '2x Book of The Ring, 2x Nuovo Fabric, 4x Fabric',
    blunt: 1.0,
    pierce: 0.7,
    slash: 1.0,
    speed: 15,
    keypage: 'N/A',
    category: 'Syndicate'
  },
  {
    id: 'r_corp_rabbit',
    name: 'R Corp. Rabbit',
    recipe: '2x Fabric, 2x Wiring, 1x Scrap Metal, 1x Book of R Corp.',
    blunt: 1.3,
    pierce: 1.2,
    slash: 0.7,
    speed: 18,
    keypage: 'Rabbit Augmentation: If taken more than 15 Damage, gain 5 Haste. RRR Suit: Increase Charge cap to 50 Maximum Charge.',
    category: 'Corporate'
  },
  {
    id: 'r_corp_rhino',
    name: 'R Corp. Rhino',
    recipe: '2x Fabric, 2x Wiring, 2x Scrap Metal, 1x Book of R Corp.',
    blunt: 0.5,
    pierce: 1.0,
    slash: 1.0,
    speed: 13,
    keypage: 'Rhino Procedure: If taken more than 15 Damage, gain 5 Protection. RRR Suit: Increase Charge cap to 50 Maximum Charge.',
    category: 'Corporate'
  },
  {
    id: 'red_mist',
    name: 'Red Mist',
    recipe: '3x Nuovo Fabric, 2x Fabric, 1x Rope, 2x Wiring, 2x Book of the Red Mist, 1x Shimmering Fabric',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.0,
    speed: 15,
    keypage: 'The Strongest: [On Use] Set Dice Value to maximum. (1 minute cooldown). Retaliate: When taking more than 20 damage in a singular attack, negate half of the incoming damage. (2 minute cooldown).',
    category: 'Legendary'
  },
  {
    id: 'reverberation_ensemble',
    name: 'Reverberation Ensemble',
    recipe: '2x Nuovo Fabric, 1x Wiring, 1x Book of Reverberation Ensemble',
    blunt: 0.8,
    pierce: 1.3,
    slash: 0.8,
    speed: 17,
    keypage: 'Nuovo Fabric: Reduces all incoming damage by 1. Only Procs [When Hit] By Pages.',
    category: 'Legendary'
  },
  {
    id: 'rosespanner_fixer',
    name: 'Rosespanner Workshop Fixer',
    recipe: '1x Nuovo Fabric, 2x Scrap Metal, 1x Wiring',
    blunt: 1.0,
    pierce: 1.3,
    slash: 0.8,
    speed: 16,
    keypage: 'Chronic Fatigue: If the enemy has 5 Tremor Count they are afflicted with -2 clash power.',
    category: 'Workshop'
  },
  {
    id: 'seven_association',
    name: 'Seven Association',
    recipe: '3x Fabric, 1x Rope, 2x Book of Seven Association',
    blunt: 1.2,
    pierce: 0.8,
    slash: 1.0,
    speed: 17,
    keypage: "Investigation: If in Seven Association Office, gain 'Investigation' page (see HP bar). Thorough Search: When killing someone after using Investigation, chance to steal 10% of their Total Ahn. Cut. In. Half.: [On Final M1] Deal True Damage Equal to Rupture on Target.",
    category: 'Association'
  },
  {
    id: 'seven_operative',
    name: 'Seven Association Operative',
    recipe: '3x Fabric, 1x Rope, 2x Book of Seven Association',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.0,
    speed: 16,
    keypage: 'Investigation. Thorough Search. Exploiting the Gap: [Clash Win] Deal Damage = 1/3 Target\'s of Rupture count on target and reduce targets Rupture Count by 1/2.',
    category: 'Association'
  },
  {
    id: 'seven_specialist',
    name: 'Seven Association Specialist',
    recipe: '3x Fabric, 1x Rope, 2x Book of Seven Association',
    blunt: 1.0,
    pierce: 0.8,
    slash: 1.3,
    speed: 17,
    keypage: "Investigation. Grasping Vulnerabilities: If Target's Damage Type weakness to incoming damage type is higher than 1.15, increase it by 15%. Opportunistic: [On Clash Win] Apply 2 Rupture and 3 Fragile.",
    category: 'Association'
  },
  {
    id: 'shi_association',
    name: 'Shi Association',
    recipe: '3x Fabric, 1x Rope, 2x Book of Shi Association',
    blunt: 1.0,
    pierce: 1.3,
    slash: 0.7,
    speed: 17,
    keypage: "Extreme Fatigue: Max Health is capped to 75%. Gain 60 Max Health. Walking the Line Of Death: When below 25% Health, increase Poise proc chance by 25%. Kizuna: Gain 1 Value Power Up on Ally Death. (Max 2). Boundary of Death: If in Shi Association Office, gain 'Boundary of Death' page (3 Light True Damage).",
    category: 'Association'
  },
  {
    id: 'shi_operative',
    name: 'Shi Association Operative',
    recipe: '3x Fabric, 1x Rope, 2x Book of Shi Association',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.3,
    speed: 17,
    keypage: 'Extreme Fatigue. Divide in Two: Having Haste increases M1 Damage by 10%. Singular Strike [On Natural 4 Roll on Boundary of Death] Sacrifice 70 HP to deal 2x Damage. Boundary of Death.',
    category: 'Association'
  },
  {
    id: 'shi_specialist',
    name: 'Shi Association Specialist',
    recipe: '3x Fabric, 1x Rope, 6x Book of Shi Association, 3x Nuovo Fabric',
    blunt: 1.2,
    pierce: 0.7,
    slash: 1.2,
    speed: 17,
    keypage: 'Extreme Fatigue. Self Neglect: Deal 20% more damage when below 30% HP. Boundary of Death.',
    category: 'Association'
  },
  {
    id: 'smiling_face_rags',
    name: 'Smiling Face Rags',
    recipe: '3x Fabric, 3x Scrap Metal, 2x Wiring',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.0,
    speed: 13,
    keypage: 'Puffy Brume: Smoke stacks on self now increase outgoing M1 Damage instead of incoming.',
    category: 'Syndicate'
  },
  {
    id: 'sneaking_suit',
    name: 'Sneaking Suit',
    recipe: 'Snake portrait at Headquarters',
    blunt: 1.2,
    pierce: 1.2,
    slash: 1.2,
    speed: 19,
    keypage: 'Cold-Hard Fists: If user has "Fist" Weapon equipped, Increase M1 Damage by 10%.',
    category: 'Special'
  },
  {
    id: 'udjat',
    name: 'Udjat',
    recipe: '2x Book Of The Udjat, 2x Fabric, 2x Nuovo Fabric',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.0,
    speed: 17,
    keypage: 'The Udjat: When entering combat, gain 10 Protection (60s CD).',
    category: 'Syndicate'
  },
  {
    id: 'brutish_stray_dog',
    name: 'Brutish Stray Dog',
    recipe: '3x Fabric, 2x Rope, 1x Book of Stray Dog',
    blunt: 0.6,
    pierce: 0.8,
    slash: 1.3,
    speed: 13,
    keypage: 'Restfulness: [On Page Use] Reduce Page Light Cost by 1. (70 Second CD). Enhancement Tattoos.',
    category: 'Syndicate'
  },
  {
    id: 'calm_stray_dog',
    name: 'Calm Stray Dog',
    recipe: '3x Fabric, 2x Rope, 1x Book of Stray Dog',
    blunt: 0.7,
    pierce: 0.7,
    slash: 1.3,
    speed: 15,
    keypage: 'Deep Breaths: 25% chance to reduce page Light cost by 2. Enhancement Tattoos.',
    category: 'Syndicate'
  },
  {
    id: 'cunning_stray_dog',
    name: 'Cunning Stray Dog',
    recipe: '3x Fabric, 2x Rope, 1x Book of Stray Dog',
    blunt: 0.8,
    pierce: 1.0,
    slash: 1.2,
    speed: 18,
    keypage: 'Double Kick: [Clash Win] deal 5 damage and inflict 4 Fragile. Enhancement Tattoos.',
    category: 'Syndicate'
  },
  {
    id: 'sweeping_fixer',
    name: 'Sweeping Fixer',
    recipe: '2x Fabric, 1x Nuovo Fabric, 1x Book',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.0,
    speed: 16,
    keypage: 'Corpse Cleanup: Gain 50 Regen Up upon gripping an enemy.',
    category: 'Fixer'
  },
  {
    id: 'thumb_capo',
    name: "Thumb Capo's Suit",
    recipe: '1x Mirror Shard, 2x Book of The Thumb, 1x Scrap Metal, 3x Fabric, 2x Nuovo Fabric, 2x Tigermark Round',
    blunt: 1.2,
    pierce: 0.9,
    slash: 0.8,
    speed: 15,
    keypage: "Thumb Officer: [With Tanglecleaver Equipped] When applying Tremor, apply 1/2 of its Count as Burn, and when applying Burn, apply 1/2 of its count as Tremor. Reload: If in Thumb Syndicate Office, gain 'Reload' page (3 Light).",
    category: 'Syndicate'
  },
  {
    id: 'thumb_soldato',
    name: 'Thumb Soldato',
    recipe: '3x Fabric, 1x Rope, 2x Book of The Thumb',
    blunt: 1.0,
    pierce: 1.0,
    slash: 0.8,
    speed: 16,
    keypage: 'Ammo Supply: If last M1 Chain is hit, gain a chance to gain 2 Bullets. Reload.',
    category: 'Syndicate'
  },
  {
    id: 'twinhook_pirate',
    name: 'Twinhook Pirate',
    recipe: '1x Twinhook, 2x Scrap Metal, 1x Mermaid Skin, 2x Fabric, 1x Book',
    blunt: 1.0,
    pierce: 1.2,
    slash: 0.8,
    speed: 16,
    keypage: 'Easy Breathing: [Clash Win] Gain 5 Poise.',
    category: 'Pirate'
  },
  {
    id: 'ting_tang_gang',
    name: 'Ting Tang Gang',
    recipe: '1x Nuovo Fabric, 1x Book',
    blunt: 1.4,
    pierce: 1.0,
    slash: 0.7,
    speed: 16,
    keypage: 'Gambit: Chance to gain Value Power Up when using dice.',
    category: 'Gang'
  },
  {
    id: 'warp_cleaner',
    name: 'WARP Corp. Cleaner',
    recipe: '1x WARP Core, 2x Fabric, 1x Rope, 1x Nuovo Fabric',
    blunt: 1.0,
    pierce: 0.7,
    slash: 1.0,
    speed: 16,
    keypage: 'Charge Suit: Increase Charge cap to 50 Maximum Charge.',
    category: 'Corporate'
  },
  {
    id: 'zwei_association',
    name: 'Zwei Association',
    recipe: '3x Fabric, 1x Rope, 2x Book of Zwei Association',
    blunt: 1.2,
    pierce: 1.0,
    slash: 0.8,
    speed: 16,
    keypage: 'Your Shield: Successful Blocks will now consume only half of the stamina and Gain Tremor. If in Zwei Association Office Gain Shield HP upon Block Hit. Stride: [Clash Win] Gain 10 Shield HP. Guardian: On [Guard Break] If you have 10 Defense Up, Consume all stacks to block the Guardbreak and gain Shield HP equivalent to count.',
    category: 'Association'
  },
  {
    id: 'zwei_operative',
    name: 'Zwei Association Operative',
    recipe: '3x Fabric, 1x Rope, 2x Book of Zwei Association',
    blunt: 0.9,
    pierce: 0.9,
    slash: 0.9,
    speed: 15,
    keypage: 'Your Shield. Easy Breathing: [Clash Win] Gain 5 Poise. Guardian.',
    category: 'Association'
  },
  {
    id: 'zwei_specialist',
    name: 'Zwei Association Specialist',
    recipe: '3x Fabric, 1x Rope, 2x Book of Zwei Association',
    blunt: 0.8,
    pierce: 1.0,
    slash: 1.3,
    speed: 17,
    keypage: 'Undercover: You are now unable to be Investigated by Seven Association members. Your Shield (heal flat 5 Shield HP instead). Light Armour: No longer takes tremor from "Your Shield". Protection Request: at 50% HP, Gain 6 Defense Up. At 25% HP, Gain 12 Protection.',
    category: 'Association'
  },
  {
    id: 'gouger_outfit',
    name: "Gouger's Outfit",
    recipe: 'Book of The Eye Gouger',
    blunt: 0.8,
    pierce: 1.3,
    slash: 1.0,
    speed: 18,
    keypage: 'Essence Of Disarming: Final Slash on Eye Gouger Critical Sets the weapon of the person hit to Brawler for a bit of time.',
    category: 'Special'
  },
  // E.G.O Outfits
  {
    id: 'fourth_match_flame',
    name: '4th Match Flame',
    recipe: 'E.G.O',
    blunt: 0.8,
    pierce: 1.0,
    slash: 0.8,
    speed: 17,
    keypage: 'Unstable Outfit: Decrease natural Health regeneration by 75%',
    category: 'EGO'
  },
  {
    id: 'apostle',
    name: 'Apostle',
    recipe: 'E.G.O',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.0,
    speed: 16,
    keypage: 'Unstable Outfit. I Will Follow Thee: Increase/Decrease resistance based on the damage type of currently equipped weapon by 0.15',
    category: 'EGO'
  },
  {
    id: 'blind_obsession',
    name: 'Blind Obsession',
    recipe: 'E.G.O',
    blunt: 0.7,
    pierce: 1.0,
    slash: 1.0,
    speed: 18,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'dimension_shredder',
    name: 'Dimension Shredder',
    recipe: 'E.G.O',
    blunt: 0.9,
    pierce: 0.8,
    slash: 1.1,
    speed: 16,
    keypage: 'Unstable Outfit. Charge Suit: Increase Charge cap to 50 Maximum Charge',
    category: 'EGO'
  },
  {
    id: 'ebony_stem',
    name: 'Ebony Stem',
    recipe: 'E.G.O',
    blunt: 1.0,
    pierce: 0.6,
    slash: 1.0,
    speed: 16,
    keypage: 'Unstable Outfit. Ebony Stem: Increase Rupture damage by 10%',
    category: 'EGO'
  },
  {
    id: 'fluid_sac',
    name: 'Fluid Sac',
    recipe: 'E.G.O',
    blunt: 1.0,
    pierce: 1.0,
    slash: 1.0,
    speed: 17,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'farmwatch',
    name: 'Farmwatch',
    recipe: 'E.G.O',
    blunt: 0.6,
    pierce: 1.3,
    slash: 1.0,
    speed: 18,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'hex_nail',
    name: 'Hex Nail',
    recipe: 'E.G.O',
    blunt: 0.8,
    pierce: 1.2,
    slash: 0.8,
    speed: 16,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'magic_bullet',
    name: 'Magic Bullet',
    recipe: 'E.G.O',
    blunt: 0.8,
    pierce: 1.0,
    slash: 0.7,
    speed: 17,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'mimicry',
    name: 'Mimicry',
    recipe: 'E.G.O',
    blunt: 0.9,
    pierce: 0.9,
    slash: 0.9,
    speed: 16,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'nihil',
    name: 'Nihil',
    recipe: 'E.G.O',
    blunt: 0.8,
    pierce: 0.7,
    slash: 0.8,
    speed: 16,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'nine_children_dragon',
    name: 'Nine Children of the Dragon',
    recipe: 'E.G.O',
    blunt: 1.0,
    pierce: 0.7,
    slash: 0.7,
    speed: 15,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'red_eyes',
    name: 'Red Eyes',
    recipe: 'E.G.O',
    blunt: 0.6,
    pierce: 1.2,
    slash: 1.0,
    speed: 17,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'regret',
    name: 'Regret',
    recipe: 'E.G.O',
    blunt: 0.6,
    pierce: 1.0,
    slash: 1.0,
    speed: 13,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'solemn_lament',
    name: 'Solemn Lament',
    recipe: 'E.G.O',
    blunt: 0.8,
    pierce: 0.7,
    slash: 1.3,
    speed: 18,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'spicebush',
    name: 'Spicebush',
    recipe: 'E.G.O',
    blunt: 0.7,
    pierce: 1.3,
    slash: 0.9,
    speed: 15,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'smile',
    name: 'Smile',
    recipe: 'E.G.O',
    blunt: 1.4,
    pierce: 0.8,
    slash: 0.7,
    speed: 19,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'telepole',
    name: 'Telepole',
    recipe: 'E.G.O',
    blunt: 1.0,
    pierce: 0.8,
    slash: 0.8,
    speed: 16,
    keypage: 'Unstable Outfit',
    category: 'EGO'
  },
  {
    id: 'waxen_pinion',
    name: 'Waxen Pinion',
    recipe: 'E.G.O',
    blunt: 0.6,
    pierce: 1.4,
    slash: 0.8,
    speed: 15,
    keypage: 'Unstable Outfit. Passion: When proccing [Stagger] on a target, inflict 5 Burn. Tempered Mind: Sanity no longer affects dice rolls.',
    category: 'EGO'
  },
  {
    id: 'sanguine_desire',
    name: 'Sanguine Desire',
    recipe: 'E.G.O',
    blunt: 1.0,
    pierce: 0.8,
    slash: 0.7,
    speed: 16,
    keypage: 'Unstable Outfit. Massive Wound: N/A',
    category: 'EGO'
  }
];

export const getOutfitCategories = () => {
  const categories = new Set(outfits.map(o => o.category));
  return Array.from(categories);
};

export const getOutfitsByCategory = (category: string) => {
  return outfits.filter(o => o.category === category);
};
